language: python
matrix:
    include:
        # Linux
        - python: 2.7
        - python: 3.4
        - python: 3.5
        - python: 3.6
        - python: 3.7
          dist: xenial

install:
  - "pip install flake8"
  - "python setup.py install"

before_script:
  - "flake8 s_tui"

script:
  - "python -m s_tui.tests.test_util_source"
  - "s-tui -t"
  - "s-tui -j"
  - "s-tui -dr"
